### ISSUE TITLE
Star names use in another project

### ISSUE THREAD

**Issue by hmlendea** [rayfowler/rotp-public#8]
Hello,

I just wanted to let you know that I wish to use the star names in a project of mine.

In short, I have a mod for Stellaris that adds thousands of new star system names to the game, from various sources (games, movies, tv series, books), and I think yours would make a good addition - especially since they are nicely put together in text files so I don't have to scavange through hundreds of wiki pages and screenshots.

Are you ok with this? Here is the pull request in my repo https://github.com/hmlendea/stellaris-ui-star-names/pull/1
I put links to your repository and also to each individual file that I used.

Let me know if you are ok with this. If you're not, I can delete that commit.

PS: It goes without saying, but you can also reuse the names from my repo in yours.

Thanks,
Hori

**Comment by rayfowler** [comment]
ok, so the main issue is that each race in ROTP has a separate name list.... there's no global list of star names that all races pull from.

In addition, each race's name list is thematic in some way so any additions to their list would need to be consistent with that theme.
